[JENKINS-65161] remove commons-digester2 from core and upgrade plugins to commons-digester3
jenkinsci/plasticscm-plugin pull request #40
Opened 2021-03-24 04:05 UTC by olamy

2021-03-24 06:26 UTC, olamy commented
https://github.com/jenkinsci/jenkins/pull/5320

2021-03-24 09:35 UTC, knapsu approved these changes
Simple changes. Looks good to me.

2021-03-30 07:23 UTC, daniel-beck requested changes
Simple and wrong: Likely creates a security vulnerability as described in https://github.com/jenkinsci/jenkins/pull/5320#issuecomment-809979530

2021-04-20 01:59 UTC, olamy commented
@knapsu  @daniel-beck fixed

2021-04-29 09:01 UTC, rsandell commented on pom.xml
> +        <!-- 1.9.4 when this merged https://github.com/stapler/stapler/pull/211 -->
Seems to be released in stapler-parent-1.262.1

2021-04-29 09:02 UTC, rsandell approved these changes

2021-04-29 09:59 UTC, olamy commented
@mig42 @knapsu @miryamGSM ping (as you are the main maintainers)

2021-04-29 10:01 UTC, mig42 commented
Thanks for finishing the PR! We'll get it merged ASAP, when we can allocate some time to also update the code in our internal repositories.

2021-05-03 10:31 UTC, alecharp approved these changes

2021-05-03 14:23 UTC, MRamonLeon approved these changes

2021-05-03 19:14 UTC, bitwiseman submitted a review, later dismissed

2021-05-04 07:36 UTC, alecharp approved these changes

2021-05-04 10:11 UTC, alecharp commented
@mig42 is there any blockers for a merge and release of the plugin? if so, please let us know, so we can try to help you.

2021-05-05 09:09 UTC, MRamonLeon approved these changes

2021-05-13 09:02 UTC, jtnord approved these changes

2021-05-24 03:23 UTC, olamy commented
@mig42 ping :)

2021-05-24 12:07 UTC, mig42 approved these changes
Changes look good to me. I'll give it a spin in my environment and merge it if everything works as expected.

2021-05-24 15:34 UTC, merged